"""Initial migration

Revision ID: 2d244a25a76e
Revises: 
Create Date: 2024-01-19 20:10:08.591243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d244a25a76e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=120), autoincrement=False, nullable=False),
    sa.Column('completed', sa.Boolean(), autoincrement=False, nullable=True, default=False),
    sa.PrimaryKeyConstraint('id', name='todo_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    # ### end Alembic commands ###
